name: Sphinx Pages
on:
  push:
    branches: [ "master" ]

permissions: write-all
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@main
      - name: Install XSLT Processor
        run: sudo apt-get install xsltproc sphinx-common
      - name: Install dependencies
        run: pip install furo myst_parser sphinx-prompt sphinx_substitution_extensions sphinx_issues sphinx_inline_tabs pygments
      - name: Checkout project sources
        uses: actions/checkout@main
        with:
          ref: master
          fetch-depth: 0
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main
      - name: Run build with Gradle Wrapper
        run: FLOATING_TOC=false gradle xmldoc sphinx
      - name: Deploy
        uses: actions/configure-pages@main
      - name: Upload artifact
        uses: actions/upload-pages-artifact@main
        with:
          # Upload entire repository
          path: 'build/sphinx'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
